import Hello from "@/components/Hello";
import LatestPosts from "@/components/LatestPosts";
import LatestWorks from "@/components/LatestWorks";
import Menu from "@/components/Menu";
import PostsGrid from "@/components/PostsGrid";
import WorksGrid from "@/components/WorksGrid";
import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" display="flex" flexDirection="column">
        <Hello>
          <Menu />
        </Hello>
        <LatestWorks>
          <WorksGrid />
        </LatestWorks>
        <LatestPosts>
          <PostsGrid />
        </LatestPosts>
      </Box>
    </>
  );
};

export default Home;
